# Site settings
title: Hoboken Made
email: team@hobokenmade.org
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: ""
url: "http://hobokenmade.github.io"
twitter_username: hobokenmade
github_username: hobokenmade

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]